package editing

// SearchType defines the matching strategy used when scanning files.
type SearchType int

const (
	// SearchText performs literal substring matching.
	SearchText SearchType = iota
	// SearchFileName matches query against file path names.
	SearchFileName
	// SearchRegex evaluates query as a regular expression.
	SearchRegex
	// SearchSymbol searches for code symbols across AST structures.
	SearchSymbol
)

// Match represents a single occurrence of a search query within a file.
type Match struct {
	Line   int    `json:"line"`
	Column int    `json:"column"`
	Text   string `json:"text"`
}

// SearchResult groups all matches found inside a specific file.
type SearchResult struct {
	Path    string  `json:"path"`
	Matches []Match `json:"matches"`
}

// Results represents a collection of search results across multiple files.
type Results []SearchResult

// SearchOptions configures the behavior of the search engine.
type SearchOptions struct {
	Root          string     `json:"root"`
	Query         string     `json:"query"`
	Type          SearchType `json:"type,omitempty"`
	CaseSensitive bool       `json:"case_sensitive"`
	WholeWord     bool       `json:"whole_word"`
	IncludeHidden bool       `json:"include_hidden"`
	MaxMatches    int        `json:"max_matches"`
	MaxFiles      int        `json:"max_files"`
}

// OperationType specifies the kind of mutation being applied to a file.
type OperationType int

const (
	// Insert specifies inserting text at a target location.
	Insert OperationType = iota
	// Replace specifies replacing a target range or text.
	Replace
	// Delete specifies removing a target range or text.
	Delete
)

// Operation represents a common model for every file modification produced by editing functions.
type Operation struct {
	Type        OperationType `json:"type"`
	File        string        `json:"file"`
	StartLine   int           `json:"start_line"`
	EndLine     int           `json:"end_line"`
	StartColumn int           `json:"start_column,omitempty"`
	EndColumn   int           `json:"end_column,omitempty"`
	OldText     string        `json:"old_text,omitempty"`
	NewText     string        `json:"new_text,omitempty"`
}

// ReplaceOptions configures string-based text replacement within a file.
type ReplaceOptions struct {
	File            string `json:"file"`
	OldText         string `json:"old_text"`
	NewText         string `json:"new_text"`
	ReplaceAll      bool   `json:"replace_all"`
	MaxReplacements int    `json:"max_replacements"`
}

// ReplaceResult returns the operations generated and total occurrences replaced during ReplaceText.
type ReplaceResult struct {
	Operations   []Operation `json:"operations"`
	Replacements int         `json:"replacements"`
}

// ReplaceRangeOptions specifies exact 1-indexed line ranges to replace within a file.
type ReplaceRangeOptions struct {
	File      string `json:"file"`
	StartLine int    `json:"start_line"`
	EndLine   int    `json:"end_line"`
	NewText   string `json:"new_text"`
}

// ReplaceRangeResult returns the modification operation generated by ReplaceRange.
type ReplaceRangeResult struct {
	Operation Operation `json:"operation"`
}

// InsertOptions specifies where and what text to insert at a specific 1-indexed line number.
type InsertOptions struct {
	File    string `json:"file"`
	Line    int    `json:"line"`
	NewText string `json:"new_text"`
}

// InsertResult returns the modification operation generated by InsertText.
type InsertResult struct {
	Operation Operation `json:"operation"`
}

// DeleteOptions specifies exact 1-indexed line ranges to remove from a file.
type DeleteOptions struct {
	File      string `json:"file"`
	StartLine int    `json:"start_line"`
	EndLine   int    `json:"end_line"`
}

// DeleteResult returns the modification operation generated by DeleteRange.
type DeleteResult struct {
	Operation Operation `json:"operation"`
}

// FilePatch groups multiple modification operations targeted at a single file path.
type FilePatch struct {
	Path       string      `json:"path"`
	Operations []Operation `json:"operations"`
}

// Patch represents an atomic bundle of file modifications grouped across multiple files.
type Patch struct {
	Files []FilePatch `json:"files"`
}
